"""Add url to news

Revision ID: 7cae82ad1fe7
Revises: 65e30a529e88
Create Date: 2025-11-29 00:15:04.385953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cae82ad1fe7'
down_revision: Union[str, Sequence[str], None] = '65e30a529e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'url')
    # ### end Alembic commands ###
