from sqlalchemy.orm import Session
from app.ai_agent.planner import planner
from app.ai_agent.tools import fetch_aggregated_news, fetch_technicals_yfinance, get_user_risk_profile
from app.ai_agent.risk_engine import risk_engine
from app.trades.models import TradeIdea
from app.ai_agent.schemas import AgentRunRequest

class AgentService:
    def run_agent(self, db: Session, request: AgentRunRequest, user_id: int):
        # 0. Pre-fetch Context for Bulk
        if "bulk" in request.goal.lower() or "find trades" in request.goal.lower():
            request.context["news_summary"] = fetch_aggregated_news()

        # 1. Plan
        action = planner.plan(request.goal, request.context)
        
        result = {"status": "completed", "action": action.action_type, "details": action.payload}

        # 2. Execute
        if action.action_type == "SUGGEST_BULK_TRADES":
            ideas_payload = action.payload.get("ideas", [])
            created_ideas = []
            
            for trade_data in ideas_payload:
                symbol = trade_data.get("symbol")
                direction = trade_data.get("direction")
                reason = trade_data.get("reason")
                
                # Technical Validation
                technicals = fetch_technicals_yfinance(symbol)
                
                # Risk Check (Simplified for bulk)
                risk_profile = get_user_risk_profile(user_id)
                risk_result = risk_engine.validate_trade(risk_profile, {"symbol": symbol, "direction": direction})
                
                if risk_result.allowed:
                    idea = TradeIdea(
                        symbol=symbol,
                        company_name=trade_data.get("company_name", symbol),
                        direction=direction,
                        time_horizon="Swing",
                        explanation=f"AI Reason: {reason}\nTechnicals: {technicals}",
                        risk_notes=f"Risk Check Passed. Max Qty: {risk_result.max_qty_allowed}",
                        educational_tip="Diversify your portfolio.",
                        status="ACTIVE"
                    )
                    db.add(idea)
                    created_ideas.append(symbol)
            
            db.commit()
            result["details"] = {"created_ideas": created_ideas, "count": len(created_ideas)}

        elif action.action_type == "SUGGEST_TRADE":
            # ... (Keep existing single trade logic if needed, or deprecate)
            pass 
                
        elif action.action_type == "GENERATE_EXPLANATION":
             result["details"] = {"explanation": "This is a mock explanation generated by the AI."}
             
        return result

agent_service = AgentService()
